server.address=0.0.0.0
server.port=9090

db_url=jdbc:postgresql://cuidagrodb.csbl5pyu9pub.us-east-1.rds.amazonaws.com:5432/cuidagro
db_user=postgres
db_pass=cuidagroadmin

api.security.token.secret=${JWT_SECRET:minha_chave}