package com.cuidagro.server.enums;

public enum UnidadeFederativa {
    ALAGOAS,
    BAHIA,
    SERGIPE,
    PERNAMBUCO,
    PARAIBA,
    RIO_GRANDE_DO_NORTE,
    CEARA,
    PIAUI,
    TOCANTINS,
    PARA,
    AMAZONAS,
    RORAIMA,
    AMAPA,
    RONDONIA,
    ACRE,
    MATO_GROSSO,
    MATO_GROSSO_DO_SUL,
    GOIAS,
    DISTRITO_FEDERAL,
    MINAS_GERAIS,
    SAO_PAULO,
    RIO_DE_JANEIRO,
    ESPIRITO_SANTO,
    PARANA,
    SANTA_CATARINA,
    RIO_GRANDE_DO_SUL;
}
